project:
  type: book
  output-dir: _output


toc: true
number-sections: true

book:
  title: "XOXO Community Survey 2024"
  author: 
   - name: Beth Duckles
     email: beth@duckles.com
  date: "October 15, 2024"
  downloads: [pdf]
  page-footer:
    left: |
     A report on engagement in the XOXO Slack Community
#  cover-image: cover.png
 # favicon: cover.png
  repo-url: https://github.com/bduckles/XOXOreport
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    background: light
    collapse-section: 1
    border: true
  chapters:
    - index.md
  #  - sections/summary.md
    - part: The Slack 
      chapters:
        - sections/Values.md
        - sections/Appreciate.md
        - sections/Concerns.md
   # - part: Platforms 
    #  chapters:
      #  - sections/Platform.md
       # - sections/Opportunity.md
       # - sections/ConcernsPlat.md
       # - sections/Name.md
 #   - part: Feels
  #    chapters:
  #    - sections/Impact.md
  #    - sections/ToTheAndys.md
