project:
  type: book
  output-dir: _output


toc: true
number-sections: true

book:
  author: [Beth Duckles, Dan Sholler, Jonah Duckles]
  date: "February 1, 2024"
  downloads: [pdf, docx]
  page-footer:
    left: |
     A report on engagement in the Astropy community
    right: |
      [![](/short_logo.png)](https://orgmycology.com)
  cover-image: cover.png
  favicon: cover.png
  site-url: https://astropy-report.orgmycology.com
  repo-url: https://github.com/orgmycology/astropy_report
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    logo: cover.png
    style: docked
    background: light
    collapse-section: 1
    border: true
  chapters:
    - index.md
    - sections/exec_summary.md
    - part: Introduction and Methods
      chapters:
        - sections/intro.md
        - sections/methods.md
    - part: sections/survey_results.md
      chapters:
        - sections/1_community_composition.md
        - sections/2_community_participation.md
        - sections/3_communication.md
        - sections/4_improving_participation.md
    - part: Recommendations
      chapters:
      - sections/community_recommendations.md
      - sections/consultant_recommendations.md
  appendices:
    - sections/references.md
    - sections/appendix.md
format:
  html:
    theme: flatly
  pdf:
    cover-image: cover.png
    documentclass: scrbook